"""Layer 6 entry point — dry-run or live order execution.

Usage:
  python run_execution.py --dry-run       (DEFAULT — no orders placed)
  python run_execution.py --execute       (requires explicit confirmation)
"""
import argparse
import json
import logging
import os
import sqlite3
import sys

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(name)s | %(message)s",
)
logger = logging.getLogger("run_execution")

TRADES_FILE = os.path.join("output", "pending_trades.json")
DB_PATH = os.path.join("cache", "jarvis.db")
DEFAULT_AUM = 10_000_000.0


def load_pending_trades() -> list[dict]:
    """Load trade list generated by Layer 4 rebalance."""
    if not os.path.exists(TRADES_FILE):
        logger.info("No pending trades file found at %s — nothing to do", TRADES_FILE)
        return []
    with open(TRADES_FILE) as f:
        return json.load(f)


def get_current_positions() -> list[dict]:
    if not os.path.exists(DB_PATH):
        return []
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    rows = conn.execute("SELECT * FROM positions WHERE is_active=1").fetchall()
    conn.close()
    return [dict(r) for r in rows]


def main():
    parser = argparse.ArgumentParser(description="JARVIS Execution Engine")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--dry-run", action="store_true", default=True,
                      help="Log what would happen — no orders placed (DEFAULT)")
    mode.add_argument("--execute", action="store_true", default=False,
                      help="Actually place orders (requires confirmation)")
    parser.add_argument("--port", type=int, default=4001,
                        help="IBKR Gateway port (4001=paper, 4002=live)")
    parser.add_argument("--aum", type=float, default=DEFAULT_AUM)
    args = parser.parse_args()

    # If --execute was given, flip dry_run off
    dry_run = not args.execute

    trades = load_pending_trades()
    if not trades:
        print("No pending trades. Run run_portfolio.py first to generate trades.")
        sys.exit(0)

    total_notional = sum(
        abs(t.get("shares", 0)) * t.get("signal_price", 0.0) for t in trades
    )

    print(f"\n{'='*60}")
    print(f"JARVIS Execution Engine")
    print(f"Mode: {'DRY-RUN' if dry_run else 'LIVE'}")
    print(f"Trades to process: {len(trades)}")
    print(f"Estimated notional: ${total_notional:,.0f}")
    print(f"{'='*60}\n")

    if not dry_run:
        live = args.port == 4002
        print(f"You are about to place {len(trades)} orders totaling ${total_notional:,.0f} in notional value.")
        print(f"Paper trading? {not live}")
        answer = input("Confirm: y/N: ").strip().lower()
        if answer != "y":
            print("Aborted.")
            sys.exit(0)

    # Import execution modules (lazy to keep dry-run fast)
    from execution.broker import IBKRBroker
    from execution.executor import execute_trade
    from execution.order_manager import OrderManager

    broker = None
    ib = None
    order_manager = OrderManager(db_path=DB_PATH)

    if not dry_run:
        broker = IBKRBroker(port=args.port)
        if not broker.connect():
            logger.error("Could not connect to IB Gateway — aborting")
            sys.exit(1)
        ib = broker.ib
        order_manager.broker = broker

    results = []
    for trade in trades:
        ticker = trade["ticker"]
        action = trade["action"]
        shares = trade["shares"]
        signal_price = trade.get("signal_price", 0.0)

        result = execute_trade(
            ticker=ticker,
            action=action,
            shares=shares,
            signal_price=signal_price,
            ib=ib,
            order_manager=order_manager,
            dry_run=dry_run,
            aum=args.aum,
            db_path=DB_PATH,
        )
        results.append(result)

    if broker:
        broker.disconnect()

    # Summary
    approved = [r for r in results if r["status"] not in ("rejected",)]
    rejected = [r for r in results if r["status"] == "rejected"]
    filled = [r for r in results if r["status"] == "filled"]
    partial = [r for r in results if r["status"] == "partial"]
    cancelled = [r for r in results if r["status"] == "cancelled"]
    dry_runs = [r for r in results if r.get("dry_run")]

    slippages = [r["slippage_bps"] for r in filled if r.get("slippage_bps") is not None]
    avg_slip = sum(slippages) / len(slippages) if slippages else 0.0
    total_commission = sum(r.get("commission") or 0.0 for r in filled)

    print(f"\n{'='*60}")
    print(f"Execution Summary")
    print(f"Mode: {'DRY-RUN' if dry_run else 'LIVE'}")
    print(f"Orders attempted:  {len(results)}")
    print(f"Approved:          {len(approved)}")
    print(f"Rejected:          {len(rejected)}")
    if dry_run:
        print(f"Would execute:     {len(dry_runs)}")
    else:
        print(f"Filled:            {len(filled)}")
        print(f"Partial:           {len(partial)}")
        print(f"Cancelled:         {len(cancelled)}")
        print(f"Avg slippage:      {avg_slip:.1f} bps")
        print(f"Total commission:  ${total_commission:.2f}")
    print(f"{'='*60}\n")

    if rejected:
        print("Rejected orders:")
        for r in rejected:
            print(f"  {r['ticker']}: {r['reason']}")


if __name__ == "__main__":
    main()
