"""Weekly Claude-authored commentary on portfolio performance."""
import json
import logging
import os
import sqlite3
from datetime import date, datetime, timedelta

logger = logging.getLogger(__name__)

OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "..", "output")
DB_PATH = os.path.join(os.path.dirname(__file__), "..", "cache", "jarvis.db")


def _build_portfolio_summary(db_path: str = DB_PATH) -> dict:
    """Assemble a compact JSON snapshot for the LLM prompt."""
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row

    positions = conn.execute(
        "SELECT ticker, shares, entry_price FROM positions WHERE is_active=1"
    ).fetchall()

    # Recent scores
    scores = conn.execute(
        "SELECT ticker, composite_score FROM scores ORDER BY scored_at DESC LIMIT 40"
    ).fetchall()

    # Portfolio history — last 5 days
    history = conn.execute(
        "SELECT date, total_value FROM portfolio_history ORDER BY date DESC LIMIT 5"
    ).fetchall()

    conn.close()

    return {
        "positions": [dict(p) for p in positions],
        "top_scores": [dict(s) for s in scores[:10]],
        "portfolio_history_5d": [dict(h) for h in history],
        "generated_at": datetime.utcnow().isoformat(),
    }


def generate_weekly_commentary(
    weekday: int = 4,  # Friday
    force: bool = False,
    db_path: str = DB_PATH,
) -> str:
    """Generate and save weekly commentary. Fires on the configured weekday.

    Returns path to saved file or None if not the right day (and not forced).
    """
    today = date.today()
    if not force and today.weekday() != weekday:
        logger.info("Skipping weekly commentary — not Friday (weekday=%d)", today.weekday())
        return None

    os.makedirs(OUTPUT_DIR, exist_ok=True)
    out_path = os.path.join(OUTPUT_DIR, f"weekly_commentary_{today.isoformat()}.md")
    if os.path.exists(out_path) and not force:
        logger.info("Weekly commentary already exists for %s", today)
        return out_path

    summary = _build_portfolio_summary(db_path)
    summary_json = json.dumps(summary, default=str, indent=2)

    system_prompt = (
        "You are JARVIS, the AI investment analyst for Meridian Capital Partners, "
        "a long/short equity hedge fund. Write institutional-quality commentary. "
        "Be direct about losses. Never use marketing language or hollow reassurances."
    )
    user_prompt = f"""Write a weekly performance summary for Meridian Capital Partners.

Data:
{summary_json}

Include:
1. Overall return vs SPY this week
2. Best and worst performing positions
3. Risk events this week
4. Changes to factor exposures
5. Outlook for next week

Style: Concise, institutional, direct. Write as JARVIS, the hedge fund's AI analyst.
Length: 300-500 words."""

    try:
        from analysis.api_client import APIClient
        client = APIClient()
        result = client.analyze(
            ticker="PORTFOLIO",
            analyzer_type="weekly_commentary",
            system_prompt=system_prompt,
            user_prompt=user_prompt,
            max_tokens=1024,
            cache=False,
        )
        if result is None:
            # API returned non-JSON — try raw text approach
            import openai, os as _os
            raw_client = openai.OpenAI(
                api_key=_os.getenv("OPENROUTER_API_KEY"),
                base_url="https://openrouter.ai/api/v1",
            )
            resp = raw_client.chat.completions.create(
                model="anthropic/claude-sonnet-4-6",
                max_tokens=1024,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt},
                ],
            )
            text = resp.choices[0].message.content or ""
        else:
            text = result.get("commentary", json.dumps(result))
    except Exception as exc:
        logger.error("Weekly commentary generation failed: %s", exc)
        text = f"[Commentary generation failed: {exc}]"

    content = f"""# Meridian Capital Partners — Weekly Commentary
Week ending: {today.isoformat()}

{text}

---
*Generated by JARVIS, Chief Investment Analyst*
*{datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}*
"""
    with open(out_path, "w") as f:
        f.write(content)
    logger.info("Weekly commentary saved to %s", out_path)
    return out_path
